[".oh-my-zsh"]
  type = "git-repo"
  url = "https://github.com/ohmyzsh/ohmyzsh.git"

[".asdf"]
  type = "git-repo"
  url = "https://github.com/asdf-vm/asdf.git"
  [".asdf".clone]
      args = ["--branch", "v0.9.0"]
  [".asdf".pull]
      args = ["origin", "v0.9.0"]

{{- if .terraform }}
[".asdf/plugins/terraform"]
  type = "git-repo"
  url = "https://github.com/asdf-community/asdf-hashicorp.git"
{{- end }}

{{- if .kubernetes }}
[".asdf/plugins/kubectl"]
  type = "git-repo"
  url = "https://github.com/asdf-community/asdf-kubectl.git"

[".asdf/plugins/helm"]
  type = "git-repo"
  url = "https://github.com/Antiarchitect/asdf-helm.git"
{{- end }}

{{- if .nodejs }}
[".asdf/plugins/nodejs"]
  type = "git-repo"
  url = "https://github.com/asdf-vm/asdf-nodejs.git"
{{- end }}

{{- if .java }}
[".asdf/plugins/java"]
  type = "git-repo"
  url = "https://github.com/halcyon/asdf-java.git"

[".asdf/plugins/maven"]
  type = "git-repo"
  url = "https://github.com/halcyon/asdf-maven.git"
{{- end }}

{{- if .hugo }}
[".asdf/plugins/hugo"]
  type = "git-repo"
  url = "https://github.com/nklmilojevic/asdf-hugo.git"
{{- end }}
