[versions]
# renovate: datasource=github-releases depName=asdf-vm/asdf
asdf = "0.10.0"

# renovate: datasource=github-releases depName=hashicorp/terraform
terraform = "1.1.9"

# renovate: datasource=github-releases depName=kubernetes/kubernetes
kubectl = "1.24.0"

# renovate: datasource=github-releases depName=helm/helm
helm = "3.8.2"

# renovate: datasource=github-releases depName=nodejs/node
nodejs = "18.2.0"

# renovate: datasource=github-releases depName=gohugoio/hugo
hugo = "0.99.1"

# renovate: datasource=github-releases depName=adoptium/temurin17-binaries extractVersionTemplate=^jdk-(?<version>.*)$
java = "17.0.3+7"

# renovate: datasource=github-releases depName=apache/maven extractVersionTemplate=^maven-(?<version>.*)$
maven = "3.8.5"

# renovate: datasource=github-releases depName=digitalocean/doctl
doctl = "1.75.0"

# renovate: datasource=github-releases depName=github/cli
github_cli = "2.8.0"
